---
name: CI - Node + React + Playwright
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install root dependencies
        run: npm install
      - name: Install Playwright in root
        run: |
          npm install -D @playwright/test
          npx playwright install --with-deps
      - name: Set up backend
        working-directory: ./backend
        run: |
          npm install
          echo "PORT=5000" >> .env
          echo "MONGO_URI=mongodb://localhost:27017/mywebapp" >> .env
          echo "JWT_SECRET=yourtestsecret" >> .env
      - name: Start backend
        working-directory: ./backend
        run: nohup node server.js &
      - name: Set up frontend
        working-directory: ./frontend
        run: npm install
      - name: Run Playwright tests
        run: >
          sudo apt-get update

          sudo apt-get install -y xvfb

          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' npx playwright test --project=chromium
