---
name: CI - Node + React + Playwright
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install root dependencies
        run: npm install
      - name: Install Playwright
        run: |
          npm install -D @playwright/test
          npx playwright install --with-deps
      - name: Set up backend
        working-directory: ./backend
        run: |
          npm install
          echo "PORT=5000" >> .env
          echo "MONGO_URI=mongodb://localhost:27017/mywebapp" >> .env
          echo "JWT_SECRET=yourtestsecret" >> .env
      - name: Start backend
        working-directory: ./backend
        run: |
          nohup node server.js > backend.log 2>&1 &
          sleep 5
          cat backend.log
      - name: Wait for backend
        run: |
          npx wait-on tcp:5000
          curl -v http://localhost:5000 || true
      - name: Seed database
        working-directory: ./backend
        run: node seedUser.js
      - name: Set up frontend
        working-directory: ./frontend
        run: |
          npm install
          echo "HOST=0.0.0.0" >> .env
          echo "PORT=3000" >> .env
          echo "BROWSER=none" >> .env
          echo "FAST_REFRESH=false" >> .env
      - name: Start frontend
        working-directory: ./frontend
        run: |
          # Install network tools for debugging
          sudo apt-get update && sudo apt-get install -y net-tools
          nohup npm start > frontend.log 2>&1 &
          sleep 15  # Increased wait time for React dev server
          cat frontend.log
          netstat -tulnp | grep 3000 || true
          curl -v http://localhost:3000 || true
      - name: Wait for frontend
        run: |
          npx wait-on --timeout 120000 --interval 2000 http://localhost:3000
          curl -v http://localhost:3000 || true
      - name: Run Playwright tests
        timeout-minutes: 10
        run: |
          xvfb-run --auto-servernum npx playwright test --project=chromium
